### ISSUE TITLE
Add support for new --link flag in COPY

### ISSUE THREAD

**Issue by mattn** [rcjsuen/dockerfile-language-service#103]
As far as I can see the code, --link is not supported yet?

![image](https://user-images.githubusercontent.com/10111/164144837-85f1a572-38bd-48e4-ab89-f2c0e1fc18f3.png)

**Comment by rcjsuen** [comment]
@mattn Thank for the bug report. Yes, this is correct and will be tracked by https://github.com/rcjsuen/dockerfile-utils/issues/108.
