### ISSUE TITLE
Add code completion support for the `--start-interval` HEALTHCHECK flag

### ISSUE THREAD

**Issue by prikhi** [rcjsuen/dockerfile-language-service#117]
The `HEALTHCHECK` command supports a `--start-interval=<duration>` flag that controls the check's interval during the specified `--start-period`:

https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by rcjsuen** [comment]
Hello, @prikhi. What feature or features are you looking for with regards to this new flag?

**Comment by prikhi** [comment]
The autocompletion doesn't include it & if I put it in manually I get an `Unknown flag: start-interval` error

**Comment by rcjsuen** [comment]
> The autocompletion doesn't include it & if I put it in manually I get an `Unknown flag: start-interval` error

Thank you for clarifying what features you are interested in.

The false positive in the linter is tracked by https://github.com/rcjsuen/dockerfile-utils/issues/115. I will make sure support for code completion is implemented as well.

**Comment by rcjsuen** [comment]
@prikhi This is now included in 0.11.0 of the language service and 0.11.0 of the language server. Thank you for bringing this to our attention!
