### ISSUE TITLE
Add lint rule forbidding single quotes in Dockerfile 

### ISSUE THREAD

**Issue by AnalyzePlatypus** [rcjsuen/dockerfile-language-service#32]
According to the [Dockerfile documentation](https://docs.docker.com/engine/reference/builder/#run), `CMD`'s array syntax must use double quotes:

> Note: The _exec_ form is parsed as a JSON array, which means that you must use double-quotes (“) around words not single-quotes (‘).
```
# Valid
CMD ["/bin/bash", "echo", "this should work"]

# Invalid
CMD ['/bin/bash', 'echo', 'mysteriously fails']
```
This build will fail with the unintelligible error `/bin/sh: 1: /bin/echo,: not found`
I just spent a few hours scratching my head, until I found [this StackOverflow answer](https://stackoverflow.com/a/30651455/6068782).

Can we include a lint rule that explicitly complains if the wrong form of quotes in used?

**Comment by rcjsuen** [comment]
Hi, @AnalyzePlatypus. Thank you for the bug report. This is being tracked by rcjsuen/dockerfile-utils#28. I will leave this open until the language service adopts the fix.
